name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # The integration tests take a long time to run,
        # so split them up into shards.
        name: [Integration]
        integration: [1]
        total_shards: [5]
        shard: [0, 1, 2, 3, 4]
        # The non-integration tests are not sharded,
        # and are added as a single job.
        include:
        - name: Mock
          integration: 0
          total_shards: 1
          shard: 0
    name: "[${{ matrix.shard }}/${{ matrix.total_shards }}] ${{ matrix.name }}"
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo gem install coveralls_reborn -v 0.20.0
        sudo gem install specific_install
        sudo gem specific_install https://github.com/infertux/bashcov -r 4ecdf0cfb8b58453d7604d1441f6a271647a4068
    - name: Test
      env:
        ACONFMGR_INTEGRATION: ${{ matrix.integration }}
        ACONFMGR_CI_SHARD: ${{ matrix.shard }}
        ACONFMGR_CI_TOTAL_SHARDS: ${{ matrix.total_shards }}
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_PARALLEL: true
        COVERALLS_FLAG_NAME: "${{ matrix.name }}"
        COVERALLS_SERVICE_NAME: github
        CI_BUILD_NUMBER: ${{ github.run_id }}
      run: |
        test/ci.sh
  finalize:
    runs-on: ubuntu-20.04
    if: always()
    needs: test
    steps:
    - run: curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_ID&payload[status]=done"
